/* 
 * home-iot-api
 *
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// ok
    /// </summary>
    [DataContract]
        public partial class LightingSummary :  IEquatable<LightingSummary>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LightingSummary" /> class.
        /// </summary>
        /// <param name="zones">zones.</param>
        /// <param name="zoneStatus">zoneStatus.</param>
        public LightingSummary(List<LightingZone> zones = default(List<LightingZone>), List<LightingZoneStatus> zoneStatus = default(List<LightingZoneStatus>))
        {
            this.Zones = zones;
            this.ZoneStatus = zoneStatus;
        }
        
        /// <summary>
        /// Gets or Sets Zones
        /// </summary>
        [DataMember(Name="zones", EmitDefaultValue=false)]
        public List<LightingZone> Zones { get; set; }

        /// <summary>
        /// Gets or Sets ZoneStatus
        /// </summary>
        [DataMember(Name="zoneStatus", EmitDefaultValue=false)]
        public List<LightingZoneStatus> ZoneStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LightingSummary {\n");
            sb.Append("  Zones: ").Append(Zones).Append("\n");
            sb.Append("  ZoneStatus: ").Append(ZoneStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LightingSummary);
        }

        /// <summary>
        /// Returns true if LightingSummary instances are equal
        /// </summary>
        /// <param name="input">Instance of LightingSummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LightingSummary input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Zones == input.Zones ||
                    this.Zones != null &&
                    input.Zones != null &&
                    this.Zones.SequenceEqual(input.Zones)
                ) && 
                (
                    this.ZoneStatus == input.ZoneStatus ||
                    this.ZoneStatus != null &&
                    input.ZoneStatus != null &&
                    this.ZoneStatus.SequenceEqual(input.ZoneStatus)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Zones != null)
                    hashCode = hashCode * 59 + this.Zones.GetHashCode();
                if (this.ZoneStatus != null)
                    hashCode = hashCode * 59 + this.ZoneStatus.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
