/* 
 * home-iot-api
 *
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Forecast
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ForecastTests
    {
        // TODO uncomment below to declare an instance variable for Forecast
        //private Forecast instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Forecast
            //instance = new Forecast();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Forecast
        /// </summary>
        [Test]
        public void ForecastInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Forecast
            //Assert.IsInstanceOfType<Forecast> (instance, "variable 'instance' is a Forecast");
        }


        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Pressure'
        /// </summary>
        [Test]
        public void PressureTest()
        {
            // TODO unit test for the property 'Pressure'
        }
        /// <summary>
        /// Test the property 'Humidity'
        /// </summary>
        [Test]
        public void HumidityTest()
        {
            // TODO unit test for the property 'Humidity'
        }
        /// <summary>
        /// Test the property 'WindSpeed'
        /// </summary>
        [Test]
        public void WindSpeedTest()
        {
            // TODO unit test for the property 'WindSpeed'
        }
        /// <summary>
        /// Test the property 'Clouds'
        /// </summary>
        [Test]
        public void CloudsTest()
        {
            // TODO unit test for the property 'Clouds'
        }
        /// <summary>
        /// Test the property 'Temperature'
        /// </summary>
        [Test]
        public void TemperatureTest()
        {
            // TODO unit test for the property 'Temperature'
        }
        /// <summary>
        /// Test the property 'Weather'
        /// </summary>
        [Test]
        public void WeatherTest()
        {
            // TODO unit test for the property 'Weather'
        }

    }

}
