/* 
 * home-iot-api
 *
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ForecastTemperature
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ForecastTemperatureTests
    {
        // TODO uncomment below to declare an instance variable for ForecastTemperature
        //private ForecastTemperature instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ForecastTemperature
            //instance = new ForecastTemperature();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ForecastTemperature
        /// </summary>
        [Test]
        public void ForecastTemperatureInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ForecastTemperature
            //Assert.IsInstanceOfType<ForecastTemperature> (instance, "variable 'instance' is a ForecastTemperature");
        }


        /// <summary>
        /// Test the property 'Low'
        /// </summary>
        [Test]
        public void LowTest()
        {
            // TODO unit test for the property 'Low'
        }
        /// <summary>
        /// Test the property 'High'
        /// </summary>
        [Test]
        public void HighTest()
        {
            // TODO unit test for the property 'High'
        }
        /// <summary>
        /// Test the property 'Morning'
        /// </summary>
        [Test]
        public void MorningTest()
        {
            // TODO unit test for the property 'Morning'
        }
        /// <summary>
        /// Test the property 'Day'
        /// </summary>
        [Test]
        public void DayTest()
        {
            // TODO unit test for the property 'Day'
        }
        /// <summary>
        /// Test the property 'Evening'
        /// </summary>
        [Test]
        public void EveningTest()
        {
            // TODO unit test for the property 'Evening'
        }
        /// <summary>
        /// Test the property 'Night'
        /// </summary>
        [Test]
        public void NightTest()
        {
            // TODO unit test for the property 'Night'
        }

    }

}
