/* 
 * home-iot-api
 *
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TemperatureSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TemperatureSummaryTests
    {
        // TODO uncomment below to declare an instance variable for TemperatureSummary
        //private TemperatureSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TemperatureSummary
            //instance = new TemperatureSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TemperatureSummary
        /// </summary>
        [Test]
        public void TemperatureSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TemperatureSummary
            //Assert.IsInstanceOfType<TemperatureSummary> (instance, "variable 'instance' is a TemperatureSummary");
        }


        /// <summary>
        /// Test the property 'Zones'
        /// </summary>
        [Test]
        public void ZonesTest()
        {
            // TODO unit test for the property 'Zones'
        }
        /// <summary>
        /// Test the property 'ZoneStatus'
        /// </summary>
        [Test]
        public void ZoneStatusTest()
        {
            // TODO unit test for the property 'ZoneStatus'
        }

    }

}
