/* 
 * home-iot-api
 *
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TemperatureZone
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TemperatureZoneTests
    {
        // TODO uncomment below to declare an instance variable for TemperatureZone
        //private TemperatureZone instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TemperatureZone
            //instance = new TemperatureZone();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TemperatureZone
        /// </summary>
        [Test]
        public void TemperatureZoneInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TemperatureZone
            //Assert.IsInstanceOfType<TemperatureZone> (instance, "variable 'instance' is a TemperatureZone");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'InputPosition'
        /// </summary>
        [Test]
        public void InputPositionTest()
        {
            // TODO unit test for the property 'InputPosition'
        }
        /// <summary>
        /// Test the property 'OutputPosition'
        /// </summary>
        [Test]
        public void OutputPositionTest()
        {
            // TODO unit test for the property 'OutputPosition'
        }
        /// <summary>
        /// Test the property 'Zone'
        /// </summary>
        [Test]
        public void ZoneTest()
        {
            // TODO unit test for the property 'Zone'
        }

    }

}
